<a href="https://colab.research.google.com/github/Santoshi-zalte/ML/blob/main/Assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [ ]:
col_names = ['Sepal_Length','Sepal_Width','Petal_Length','Petal_Width','Species']
iris = pd.read_csv(csv_url, names = col_names)
#iris = pd.read_csv(csv_url, header = None)
##print(iris)

df = pd.DataFrame(iris)
##print(df)
df.head()
##df1.isnull()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
x=df.loc[:,["Sepal_Width","Petal_Width"]]
x

     Sepal_Width  Petal_Width
0            3.5          0.2
1            3.0          0.2
2            3.2          0.2
3            3.1          0.2
4            3.6          0.2
..           ...          ...
145          3.0          2.3
146          2.5          1.9
147          3.0          2.0
148          3.4          2.3
149          3.0          1.8

[150 rows x 2 columns]

In [ ]:
y=df["Petal_Width"]
y.head()

0    0.2
1    0.2
2    0.2
3    0.2
4    0.2
Name: Petal_Width, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(x,y,test_size=0.30,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.fit_transform(xtest)

In [ ]:
df=pd.read_csv("/content/PlayTennis.csv")
df

     Outlook Temperature Humidity    Wind Play Tennis
0      Sunny         Hot     High    Weak          No
1      Sunny         Hot     High  Strong          No
2   Overcast         Hot     High    Weak         Yes
3       Rain        Mild     High    Weak         Yes
4       Rain        Cool   Normal    Weak         Yes
5       Rain        Cool   Normal  Strong          No
6   Overcast        Cool   Normal  Strong         Yes
7      Sunny        Mild     High    Weak          No
8      Sunny        Cool   Normal    Weak         Yes
9       Rain        Mild   Normal    Weak         Yes
10     Sunny        Mild   Normal  Strong         Yes
11  Overcast        Mild     High  Strong         Yes
12  Overcast         Hot   Normal    Weak         Yes
13      Rain        Mild     High  Strong          No

In [ ]:
import pandas as pd

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.30,random_state=0)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gaussian=GaussianNB
model=gaussian.fit(x_train, y_train)

NameError: ignored